version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:password@db:5432/auth-mc-1
      - KEY_FOR_SAVE_OTP_REDIS=hirakkkk
      - DEV_BASE_URL=http://localhost:3001
      - JWT_ACCESS_SECRET=hirakkkk
      - JWT_REFRESH_SECRET=hirakkkk
      - USER_EMAIL=royhiark@gmail.com
      - EMAIL_SERVICE=gmail
      - USER_EMAIL_KEY=jvao xmrf azkm ijxq
      - TWILIO_ACCOUNT_SID=ACfaa49acfde9b2f7bbe3a669a0a9573d8
      - TWILIO_AUTH_TOKEN=ef821a9f662a4c2d0d62ca9cf1ae6aed
      - TWILIO_PHONE_NUMBER=+12568297541
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth-mc-1
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
volumes:
  db_data:
